/**
 * @file seed-recipes.ts
 * @description Preinstalled example recipes of the cookbook.
 *
 * These recipes ship with the app so the library is never empty: they show up in every
 * category page and in the "All recipes" view next to the recipes generated by the user.
 * They live only in this file and are merged into the Firebase results at read time, which means
 * they are never written to the database and therefore can never be duplicated by repeated loads.
 * Their ids use the stable `seed-` prefix so the library service can resolve them
 * without a network request (see RecipeLibraryService.getRecipeById).
 */
import type { CookbookRecipeRecord } from '../recipe-library.service';

/** Prefix of every preinstalled recipe id; identifies records that must not reach Firebase. */
export const SEED_RECIPE_ID_PREFIX = 'seed-';

/**
 * The preinstalled recipes, one per cuisine category, newest first.
 * The timestamps are fixed points in the past so the sort order of the cookbook stays stable
 * and freshly generated recipes always appear above the preinstalled ones.
 */
export const seedRecipes: readonly CookbookRecipeRecord[] = [
  {
    id: 'seed-italian-tomato-risotto',
    title: 'Tomato and Basil Risotto',
    description: 'A creamy Arborio risotto with slow-roasted tomatoes, white wine and a generous finish of parmesan and fresh basil.',
    estimatedMinutes: 35,
    ingredients: [
      '320 g Arborio rice',
      '500 g Ripe tomatoes',
      '1 piece Onion',
      '60 g Parmesan',
      '1 l Vegetable stock',
      '2 piece Garlic cloves',
      '120 ml Dry white wine',
      '40 g Butter',
      '1 bunch Fresh basil',
      '2 tbsp Olive oil',
      'Salt and black pepper',
    ],
    extraIngredients: [
      '1 l Vegetable stock',
      '2 piece Garlic cloves',
      '120 ml Dry white wine',
      '40 g Butter',
      '1 bunch Fresh basil',
      '2 tbsp Olive oil',
      'Salt and black pepper',
    ],
    steps: [
      'Roast the tomatoes: Halve the tomatoes, toss them with olive oil, salt and pepper and roast them at 200 °C for 20 minutes until they collapse.',
      'Build the base: Dice the onion and garlic and sweat them in half of the butter until glassy, then add the rice and toast it for two minutes.',
      'Deglaze with wine: Pour in the white wine and stir until it has almost completely evaporated.',
      'Add the stock: Add the hot stock one ladle at a time, stirring, and only add the next ladle once the previous one is absorbed. This takes about 18 minutes.',
      'Fold in the tomatoes: Stir the roasted tomatoes with their juices into the risotto and season with salt and pepper.',
      'Finish and serve: Take the pan off the heat, beat in the remaining butter and the grated parmesan, cover for two minutes and serve with torn basil.',
    ],
    stepDetails: [
      { title: 'Roast the tomatoes', instruction: 'Halve the tomatoes, toss them with olive oil, salt and pepper and roast them at 200 °C for 20 minutes until they collapse.', cook: 2, parallel: true, durationMinutes: 20 },
      { title: 'Build the base', instruction: 'Dice the onion and garlic and sweat them in half of the butter until glassy, then add the rice and toast it for two minutes.', cook: 1, parallel: true, durationMinutes: 6 },
      { title: 'Deglaze with wine', instruction: 'Pour in the white wine and stir until it has almost completely evaporated.', cook: 1, parallel: false, durationMinutes: 3 },
      { title: 'Add the stock', instruction: 'Add the hot stock one ladle at a time, stirring, and only add the next ladle once the previous one is absorbed.', cook: 1, parallel: false, durationMinutes: 18 },
      { title: 'Fold in the tomatoes', instruction: 'Stir the roasted tomatoes with their juices into the risotto and season with salt and pepper.', cook: 2, parallel: false, durationMinutes: 3 },
      { title: 'Finish and serve', instruction: 'Take the pan off the heat, beat in the remaining butter and the grated parmesan, cover for two minutes and serve with torn basil.', cook: 1, parallel: false, durationMinutes: 4 },
    ],
    nutrition: {
      perPortion: { calories: 520, protein: 14, carbs: 72, fat: 18 },
      total: { calories: 2080, protein: 56, carbs: 288, fat: 72 },
    },
    ingredientCoverage: 100,
    cuisine: 'italian',
    categorySlug: 'Italian',
    cookingTime: 'medium',
    difficulty: 'Medium',
    dietLabel: 'vegetarian',
    diets: ['vegetarian'],
    cooks: 2,
    portions: 4,
    likes: 18,
    createdAt: '2025-11-02T17:30:00.000Z',
    requestedAt: '2025-11-02T17:30:00.000Z',
    sourceIngredients: [
      { name: 'Arborio rice', quantity: 320, unit: 'gram' },
      { name: 'Tomatoes', quantity: 500, unit: 'gram' },
      { name: 'Onion', quantity: 1, unit: 'piece' },
      { name: 'Parmesan', quantity: 60, unit: 'gram' },
    ],
  },
  {
    id: 'seed-german-potato-goulash',
    title: 'Bavarian Potato Goulash',
    description: 'Hearty potatoes simmered with smoked sausage, sweet paprika and caraway until the sauce is thick enough to coat a spoon.',
    estimatedMinutes: 50,
    ingredients: [
      '1 kg Potatoes',
      '300 g Smoked sausage',
      '2 piece Onion',
      '2 piece Bell pepper',
      '2 tbsp Sweet paprika powder',
      '1 tsp Caraway seeds',
      '700 ml Beef stock',
      '2 tbsp Tomato paste',
      '1 tbsp Butterschmalz',
      '1 splash White wine vinegar',
      'Salt, pepper and marjoram',
    ],
    extraIngredients: [
      '2 tbsp Sweet paprika powder',
      '1 tsp Caraway seeds',
      '700 ml Beef stock',
      '2 tbsp Tomato paste',
      '1 tbsp Butterschmalz',
      '1 splash White wine vinegar',
      'Salt, pepper and marjoram',
    ],
    steps: [
      'Prepare the vegetables: Peel the potatoes and cut them into bite-sized cubes, dice the onions finely and cut the bell peppers into strips.',
      'Render the sausage: Slice the sausage and fry it in the Butterschmalz until the edges are crisp, then lift it out and set it aside.',
      'Sweat the onions: Fry the onions in the sausage fat until golden, stir in the tomato paste and roast it for one minute.',
      'Bloom the spices: Take the pot off the heat, stir in the paprika and caraway so they do not burn, then deglaze immediately with a splash of vinegar and the stock.',
      'Simmer the goulash: Add the potatoes and peppers, cover and simmer for 25 minutes until the potatoes are soft and the sauce has thickened.',
      'Season and serve: Return the sausage to the pot, season with salt, pepper and marjoram and let it rest for five minutes before serving.',
    ],
    stepDetails: [
      { title: 'Prepare the vegetables', instruction: 'Peel the potatoes and cut them into bite-sized cubes, dice the onions finely and cut the bell peppers into strips.', cook: 2, parallel: true, durationMinutes: 12 },
      { title: 'Render the sausage', instruction: 'Slice the sausage and fry it in the Butterschmalz until the edges are crisp, then lift it out and set it aside.', cook: 1, parallel: true, durationMinutes: 6 },
      { title: 'Sweat the onions', instruction: 'Fry the onions in the sausage fat until golden, stir in the tomato paste and roast it for one minute.', cook: 1, parallel: false, durationMinutes: 5 },
      { title: 'Bloom the spices', instruction: 'Take the pot off the heat, stir in the paprika and caraway so they do not burn, then deglaze immediately with a splash of vinegar and the stock.', cook: 1, parallel: false, durationMinutes: 2 },
      { title: 'Simmer the goulash', instruction: 'Add the potatoes and peppers, cover and simmer for 25 minutes until the potatoes are soft and the sauce has thickened.', cook: 1, parallel: false, durationMinutes: 25 },
      { title: 'Season and serve', instruction: 'Return the sausage to the pot, season with salt, pepper and marjoram and let it rest for five minutes before serving.', cook: 2, parallel: false, durationMinutes: 5 },
    ],
    nutrition: {
      perPortion: { calories: 610, protein: 24, carbs: 58, fat: 30 },
      total: { calories: 2440, protein: 96, carbs: 232, fat: 120 },
    },
    ingredientCoverage: 100,
    cuisine: 'german',
    categorySlug: 'German',
    cookingTime: 'complex',
    difficulty: 'Complex',
    dietLabel: null,
    diets: [],
    cooks: 2,
    portions: 4,
    likes: 14,
    createdAt: '2025-10-24T16:10:00.000Z',
    requestedAt: '2025-10-24T16:10:00.000Z',
    sourceIngredients: [
      { name: 'Potatoes', quantity: 1, unit: 'kg' },
      { name: 'Smoked sausage', quantity: 300, unit: 'gram' },
      { name: 'Onion', quantity: 2, unit: 'piece' },
      { name: 'Bell pepper', quantity: 2, unit: 'piece' },
    ],
  },
  {
    id: 'seed-japanese-miso-salmon-donburi',
    title: 'Miso Glazed Salmon Donburi',
    description: 'Salmon fillets lacquered with a sweet-salty miso glaze on a bowl of warm rice, finished with quick-pickled cucumber.',
    estimatedMinutes: 25,
    ingredients: [
      '2 piece Salmon fillet',
      '300 g Sushi rice',
      '1 piece Cucumber',
      '2 piece Spring onion',
      '2 tbsp White miso paste',
      '2 tbsp Mirin',
      '1 tbsp Soy sauce',
      '1 tsp Honey',
      '2 tbsp Rice vinegar',
      '1 tsp Toasted sesame seeds',
      '1 tsp Sesame oil',
    ],
    extraIngredients: [
      '2 tbsp White miso paste',
      '2 tbsp Mirin',
      '1 tbsp Soy sauce',
      '1 tsp Honey',
      '2 tbsp Rice vinegar',
      '1 tsp Toasted sesame seeds',
      '1 tsp Sesame oil',
    ],
    steps: [
      'Cook the rice: Rinse the sushi rice until the water runs clear, then cook it with 1.2 parts water and let it steam covered for 10 minutes.',
      'Mix the glaze: Whisk the miso paste, mirin, soy sauce and honey into a smooth, shiny glaze.',
      'Pickle the cucumber: Slice the cucumber thinly, toss it with the rice vinegar and a pinch of salt and let it sit while the rice cooks.',
      'Glaze the salmon: Pat the salmon dry, brush it generously with the glaze and grill it under high heat for 6 to 8 minutes until the top caramelizes.',
      'Build the bowls: Fluff the rice with sesame oil, spoon it into bowls and place the salmon on top.',
      'Garnish: Add the pickled cucumber, scatter sliced spring onion and sesame seeds over the bowl and serve immediately.',
    ],
    stepDetails: [
      { title: 'Cook the rice', instruction: 'Rinse the sushi rice until the water runs clear, then cook it with 1.2 parts water and let it steam covered for 10 minutes.', cook: 1, parallel: true, durationMinutes: 18 },
      { title: 'Mix the glaze', instruction: 'Whisk the miso paste, mirin, soy sauce and honey into a smooth, shiny glaze.', cook: 2, parallel: true, durationMinutes: 3 },
      { title: 'Pickle the cucumber', instruction: 'Slice the cucumber thinly, toss it with the rice vinegar and a pinch of salt and let it sit while the rice cooks.', cook: 2, parallel: true, durationMinutes: 5 },
      { title: 'Glaze the salmon', instruction: 'Pat the salmon dry, brush it generously with the glaze and grill it under high heat for 6 to 8 minutes until the top caramelizes.', cook: 2, parallel: false, durationMinutes: 8 },
      { title: 'Build the bowls', instruction: 'Fluff the rice with sesame oil, spoon it into bowls and place the salmon on top.', cook: 1, parallel: false, durationMinutes: 3 },
      { title: 'Garnish', instruction: 'Add the pickled cucumber, scatter sliced spring onion and sesame seeds over the bowl and serve immediately.', cook: 1, parallel: false, durationMinutes: 2 },
    ],
    nutrition: {
      perPortion: { calories: 640, protein: 38, carbs: 68, fat: 22 },
      total: { calories: 1280, protein: 76, carbs: 136, fat: 44 },
    },
    ingredientCoverage: 100,
    cuisine: 'japanese',
    categorySlug: 'Japanese',
    cookingTime: 'medium',
    difficulty: 'Medium',
    dietLabel: null,
    diets: [],
    cooks: 2,
    portions: 2,
    likes: 11,
    createdAt: '2025-10-11T18:45:00.000Z',
    requestedAt: '2025-10-11T18:45:00.000Z',
    sourceIngredients: [
      { name: 'Salmon fillet', quantity: 2, unit: 'piece' },
      { name: 'Sushi rice', quantity: 300, unit: 'gram' },
      { name: 'Cucumber', quantity: 1, unit: 'piece' },
      { name: 'Spring onion', quantity: 2, unit: 'piece' },
    ],
  },
  {
    id: 'seed-indian-chana-masala',
    title: 'Chana Masala with Coconut Rice',
    description: 'Chickpeas braised in a tomato and ginger masala, served with fragrant coconut basmati rice and plenty of coriander.',
    estimatedMinutes: 40,
    ingredients: [
      '480 g Chickpeas',
      '400 g Chopped tomatoes',
      '1 piece Onion',
      '300 g Basmati rice',
      '20 g Fresh ginger',
      '3 piece Garlic cloves',
      '200 ml Coconut milk',
      '2 tsp Garam masala',
      '1 tsp Ground cumin',
      '1 tsp Ground turmeric',
      '1 bunch Fresh coriander',
      '2 tbsp Vegetable oil',
      'Salt and one lime',
    ],
    extraIngredients: [
      '20 g Fresh ginger',
      '3 piece Garlic cloves',
      '200 ml Coconut milk',
      '2 tsp Garam masala',
      '1 tsp Ground cumin',
      '1 tsp Ground turmeric',
      '1 bunch Fresh coriander',
      '2 tbsp Vegetable oil',
      'Salt and one lime',
    ],
    steps: [
      'Start the rice: Rinse the basmati rice, then simmer it with half of the coconut milk, water and a pinch of salt for 12 minutes and let it rest covered.',
      'Make the masala paste: Blend the ginger, garlic and half of the onion into a coarse paste.',
      'Fry the aromatics: Fry the remaining sliced onion in oil until deep golden, add the paste and fry for another two minutes.',
      'Toast the spices: Stir in garam masala, cumin and turmeric and toast them for 30 seconds until fragrant.',
      'Braise the chickpeas: Add the tomatoes and the drained chickpeas, season with salt and simmer uncovered for 20 minutes until the sauce is glossy.',
      'Finish and serve: Stir in the remaining coconut milk, adjust with lime juice and serve over the coconut rice with plenty of coriander.',
    ],
    stepDetails: [
      { title: 'Start the rice', instruction: 'Rinse the basmati rice, then simmer it with half of the coconut milk, water and a pinch of salt for 12 minutes and let it rest covered.', cook: 2, parallel: true, durationMinutes: 18 },
      { title: 'Make the masala paste', instruction: 'Blend the ginger, garlic and half of the onion into a coarse paste.', cook: 1, parallel: true, durationMinutes: 5 },
      { title: 'Fry the aromatics', instruction: 'Fry the remaining sliced onion in oil until deep golden, add the paste and fry for another two minutes.', cook: 1, parallel: false, durationMinutes: 8 },
      { title: 'Toast the spices', instruction: 'Stir in garam masala, cumin and turmeric and toast them for 30 seconds until fragrant.', cook: 1, parallel: false, durationMinutes: 1 },
      { title: 'Braise the chickpeas', instruction: 'Add the tomatoes and the drained chickpeas, season with salt and simmer uncovered for 20 minutes until the sauce is glossy.', cook: 1, parallel: false, durationMinutes: 20 },
      { title: 'Finish and serve', instruction: 'Stir in the remaining coconut milk, adjust with lime juice and serve over the coconut rice with plenty of coriander.', cook: 2, parallel: false, durationMinutes: 4 },
    ],
    nutrition: {
      perPortion: { calories: 585, protein: 19, carbs: 84, fat: 18 },
      total: { calories: 2340, protein: 76, carbs: 336, fat: 72 },
    },
    ingredientCoverage: 100,
    cuisine: 'indian',
    categorySlug: 'Indian',
    cookingTime: 'medium',
    difficulty: 'Medium',
    dietLabel: 'vegan',
    diets: ['vegan', 'vegetarian'],
    cooks: 2,
    portions: 4,
    likes: 9,
    createdAt: '2025-09-28T15:05:00.000Z',
    requestedAt: '2025-09-28T15:05:00.000Z',
    sourceIngredients: [
      { name: 'Chickpeas', quantity: 480, unit: 'gram' },
      { name: 'Chopped tomatoes', quantity: 400, unit: 'gram' },
      { name: 'Onion', quantity: 1, unit: 'piece' },
      { name: 'Basmati rice', quantity: 300, unit: 'gram' },
    ],
  },
  {
    id: 'seed-gourmet-scallops-cauliflower',
    title: 'Seared Scallops on Cauliflower Purée',
    description: 'Golden-crusted scallops on a silky cauliflower purée with brown butter, capers and a bright lemon finish.',
    estimatedMinutes: 45,
    ingredients: [
      '8 piece Scallops',
      '600 g Cauliflower',
      '200 ml Whole milk',
      '1 piece Lemon',
      '80 g Butter',
      '1 tbsp Capers',
      '100 ml Cream',
      '1 tbsp Clarified butter',
      '1 tsp Sherry vinegar',
      '10 g Chives',
      'Fleur de sel and white pepper',
    ],
    extraIngredients: [
      '80 g Butter',
      '1 tbsp Capers',
      '100 ml Cream',
      '1 tbsp Clarified butter',
      '1 tsp Sherry vinegar',
      '10 g Chives',
      'Fleur de sel and white pepper',
    ],
    steps: [
      'Cook the cauliflower: Cut the cauliflower into small florets and simmer them in the milk with a pinch of salt for 15 minutes until very soft.',
      'Blend the purée: Blend the drained florets with the cream and 30 g of the butter until completely smooth, then season with white pepper and keep warm.',
      'Prepare the scallops: Pat the scallops thoroughly dry on both sides and season them with salt just before searing.',
      'Sear the scallops: Sear them in smoking hot clarified butter for 90 seconds per side until a deep golden crust forms, then take them out of the pan.',
      'Make the brown butter: Melt the remaining butter in the same pan until it smells nutty, then add the capers and deglaze with sherry vinegar and lemon juice.',
      'Plate the dish: Spoon the purée onto warm plates, set the scallops on top, spoon over the caper butter and finish with chives and fleur de sel.',
    ],
    stepDetails: [
      { title: 'Cook the cauliflower', instruction: 'Cut the cauliflower into small florets and simmer them in the milk with a pinch of salt for 15 minutes until very soft.', cook: 1, parallel: true, durationMinutes: 18 },
      { title: 'Blend the purée', instruction: 'Blend the drained florets with the cream and 30 g of the butter until completely smooth, then season with white pepper and keep warm.', cook: 1, parallel: false, durationMinutes: 6 },
      { title: 'Prepare the scallops', instruction: 'Pat the scallops thoroughly dry on both sides and season them with salt just before searing.', cook: 2, parallel: true, durationMinutes: 5 },
      { title: 'Sear the scallops', instruction: 'Sear them in smoking hot clarified butter for 90 seconds per side until a deep golden crust forms, then take them out of the pan.', cook: 2, parallel: false, durationMinutes: 4 },
      { title: 'Make the brown butter', instruction: 'Melt the remaining butter in the same pan until it smells nutty, then add the capers and deglaze with sherry vinegar and lemon juice.', cook: 2, parallel: false, durationMinutes: 4 },
      { title: 'Plate the dish', instruction: 'Spoon the purée onto warm plates, set the scallops on top, spoon over the caper butter and finish with chives and fleur de sel.', cook: 1, parallel: false, durationMinutes: 4 },
    ],
    nutrition: {
      perPortion: { calories: 430, protein: 27, carbs: 21, fat: 26 },
      total: { calories: 860, protein: 54, carbs: 42, fat: 52 },
    },
    ingredientCoverage: 100,
    cuisine: 'gourmet',
    categorySlug: 'Gourmet',
    cookingTime: 'complex',
    difficulty: 'Complex',
    dietLabel: null,
    diets: [],
    cooks: 2,
    portions: 2,
    likes: 7,
    createdAt: '2025-09-15T19:20:00.000Z',
    requestedAt: '2025-09-15T19:20:00.000Z',
    sourceIngredients: [
      { name: 'Scallops', quantity: 8, unit: 'piece' },
      { name: 'Cauliflower', quantity: 600, unit: 'gram' },
      { name: 'Whole milk', quantity: 200, unit: 'ml' },
      { name: 'Lemon', quantity: 1, unit: 'piece' },
    ],
  },
];

/**
 * Checks whether a recipe id belongs to a preinstalled recipe.
 * @param recipeId - Id from a route or a Firebase record.
 * @returns True when the id uses the seed prefix.
 */
export function isSeedRecipeId(recipeId: string): boolean {
  return recipeId.startsWith(SEED_RECIPE_ID_PREFIX);
}

/**
 * Looks up a preinstalled recipe by its id.
 * @param recipeId - Id from the recipe detail route.
 * @returns The preinstalled recipe, or null when the id is unknown.
 */
export function findSeedRecipe(recipeId: string): CookbookRecipeRecord | null {
  return seedRecipes.find((recipe) => recipe.id === recipeId) ?? null;
}

/**
 * Adds the preinstalled recipes to the recipes loaded from Firebase.
 * A stored recipe with the same id always wins, so nothing is listed twice.
 * @param storedRecipes - Recipes read from Firebase (may be empty when the database is unreachable).
 * @returns The stored recipes plus every preinstalled recipe that is not already contained.
 */
export function mergeWithSeedRecipes(storedRecipes: CookbookRecipeRecord[]): CookbookRecipeRecord[] {
  const storedIds = new Set(storedRecipes.map((recipe) => recipe.id));
  return [...storedRecipes, ...seedRecipes.filter((recipe) => !storedIds.has(recipe.id))];
}
