/**
 * @file recipe-library.service.spec.ts
 * @description Unit tests for the cookbook library: merging the preinstalled recipes with Firebase,
 * resolving them by id and keeping them out of the database.
 */
import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { HttpTestingController, provideHttpClientTesting } from '@angular/common/http/testing';

import { RecipeLibraryService } from './recipe-library.service';
import { seedRecipes } from './cookbook/seed-recipes';
import { environment } from '../environments/environment';

const recipesUrl = `${environment.firebaseDatabaseUrl}/recipes.json`;

describe('RecipeLibraryService', () => {
  let service: RecipeLibraryService;
  let httpMock: HttpTestingController;

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideHttpClient(), provideHttpClientTesting()],
    });

    service = TestBed.inject(RecipeLibraryService);
    httpMock = TestBed.inject(HttpTestingController);
  });

  afterEach(() => {
    httpMock.verify();
  });

  it('lists every preinstalled recipe when the database is empty', async () => {
    const recipesPromise = service.getAllRecipes();
    httpMock.expectOne(recipesUrl).flush(null);

    const recipes = await recipesPromise;

    expect(recipes.map((recipe) => recipe.id)).toEqual(seedRecipes.map((recipe) => recipe.id));
  });

  it('still lists the preinstalled recipes when Firebase is unreachable', async () => {
    const recipesPromise = service.getAllRecipes();
    httpMock.expectOne(recipesUrl).error(new ProgressEvent('error'), { status: 0, statusText: 'offline' });

    const recipes = await recipesPromise;

    expect(recipes.length).toBe(seedRecipes.length);
  });

  it('merges the preinstalled recipes with the stored ones without duplicating them', async () => {
    const recipesPromise = service.getAllRecipes();
    httpMock.expectOne(recipesUrl).flush({
      'firebase-1': {
        title: 'Generated recipe',
        description: 'A recipe generated by a user.',
        estimatedMinutes: 25,
        ingredients: ['200 g Pasta'],
        steps: ['Cook the pasta: Boil it until al dente.'],
        cuisine: 'italian',
        categorySlug: 'Italian',
        cookingTime: 'medium',
        difficulty: 'Medium',
        cooks: 1,
        portions: 2,
        likes: 0,
        createdAt: '2026-01-05T10:00:00.000Z',
        requestedAt: '2026-01-05T10:00:00.000Z',
      },
    });

    const recipes = await recipesPromise;

    expect(recipes.length).toBe(seedRecipes.length + 1);
    expect(recipes[0].id).toBe('firebase-1');
    expect(recipes.filter((recipe) => recipe.id === 'seed-italian-tomato-risotto').length).toBe(1);
  });

  it('finds a preinstalled recipe by its id without calling Firebase', async () => {
    const recipe = await service.getRecipeById('seed-japanese-miso-salmon-donburi');

    expect(recipe?.title).toBe('Miso Glazed Salmon Donburi');
    expect(recipe?.stepDetails?.length).toBeGreaterThan(0);
    expect(recipe?.nutrition?.perPortion.calories).toBeGreaterThan(0);
  });

  it('assigns every preinstalled recipe to an existing cookbook category', () => {
    const categorySlugs = ['German', 'Italian', 'Indian', 'Japanese', 'Gourmet', 'Fusion'];

    for (const recipe of seedRecipes) {
      expect(categorySlugs).toContain(recipe.categorySlug);
      expect(recipe.id.startsWith('seed-')).toBe(true);
    }
  });

  it('counts likes of a preinstalled recipe without writing them to Firebase', async () => {
    const seedRecipe = seedRecipes.find((recipe) => recipe.id === 'seed-indian-chana-masala');

    const likes = await service.incrementRecipeLike('seed-indian-chana-masala');

    expect(likes).toBe((seedRecipe?.likes ?? 0) + 1);
    expect((await service.getRecipeById('seed-indian-chana-masala'))?.likes).toBe(likes);
  });
});
